server:
    port: 8080
    sessionTimeout: 20000

multipart:
    maxFileSize: 100MB
    maxRequestSize: 100MB
    
spring:
    profiles:
        active: prod
    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://localhost:3306/nodesoft?useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8
        databaseName: 
        serverName: 
        username: root
        password: 
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

    jpa:
        database-platform: org.hibernate.dialect.MySQLInnoDBDialect
        database: MYSQL
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
            
    data:
        elasticsearch:
            cluster-name:
            cluster-nodes: localhost:9200
    thymeleaf:
        mode: XHTML
        cache: true

metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: nodesoft

http:
    cache:
        timeToLiveInDays: 31

cache:
    timeToLiveSeconds: 3600
    hazelcast:
        debug: false
        stickySession: false
        backupCount: 1
    ehcache:
        maxBytesLocalHeap: 256M
